<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<PublishSingleFile>true</PublishSingleFile>
		<UseAppHost>true</UseAppHost>
		<AssemblyName>Vyapari.Maths</AssemblyName>
		<RootNamespace>Vyapari.Maths</RootNamespace>
		<LangVersion>8.0</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="Numbers.fs"/>
		<Compile Include="Vector.fs"/>
		<Compile Include="Matrix.fs"/>
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Utils\Utils.fsproj" />
	</ItemGroup>

</Project>
