<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <IsTestProject>false</IsTestProject>
        <OutputType>Library</OutputType>
        <AssemblyName>Vyapari</AssemblyName>
        <RootNamespace>Vyapari</RootNamespace>
        <LangVersion>10.0</LangVersion>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Utils.fs" />
        <Compile Include="Definitions.fs" />
        <Compile Include="Data.fs" />
        <Compile Include="Buffer.fs" />
        <Compile Include="DataItems.fs" />
        <Compile Include="Sockets.fs" />
        <Compile Include="Execution.fs" />
        <Compile Include="Gemini.fs" />
        <Compile Include="Tradier.fs" />
    </ItemGroup>
</Project>
